version: '3.9'
services:
  db:
      container_name: ria-postgres
      image: postgis/postgis:latest
      restart: unless-stopped
      env_file:
        - .env
      healthcheck:
        test: [ "CMD", "pg_isready", "-q", "-d", "${DB_NAME}", "-U", "${DB_USER}" ]
        timeout: 45s
        interval: 5s
        retries: 20
      ports:
        - "${POSTGRES_PORT}:5432"
      shm_size: 1gb
      volumes:
        - pg_data:/var/lib/postgresql/data/
        - ./db/init_database.sh:/docker-entrypoint-initdb.d/init_database.sh
        - ./db/data/municipalities.sql:/etc/postgresql/municipalities.sql
        - ./db/postgresql.conf:/etc/postgresql/postgresql.conf
      # command: postgres -c config_file=/etc/postgresql/postgresql.conf
      networks:
        - backend
  
volumes:
  pg_data: {}

networks:
  backend: {}